name: Parallel Cypress Tests
on: push
jobs:
  test:
    name: Cypress Run
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false  # Continue running other tests even if one fails
      matrix:
        containers: [1, 2, 3]  # Adjust the array size to increase or decrease parallelism
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: 'Actions Example'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
